name: Chris Singer
description: "Website for Chris Singer, junior developer and student located in Columbus, OH. Ruby, SQL, and food enthusiast."

url: "http://localhost:4000"

paginate: 10

markdown: rdiscount
permalink: pretty
highlighter: pygments