name: Chris Singer
description: "Website for Chris Singer, newly minted Software Engineer living in Columbus, OH. Ruby, clean code, delicious foods, and video game enthusiast."

url: "http://localhost:4000"

paginate: 10

markdown: rdiscount
permalink: pretty
highlighter: pygments
sass:
    sass_dir: _sass
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - wercker.yml